whitelist_rules:
  - missing_docs
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - duplicate_imports
  - reduce_boolean
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_import
  - unused_setter_value
  - redundant_void_return
  - todo
  - yoda_condition
  - closure_body_length
  - closure_parameter_position
  - empty_parentheses_with_trailing_closure
  - unneeded_parentheses_in_closure_argument
  - single_test_class
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_type_annotation
  - opening_brace
  - closing_brace
  - comma
  - colon
  - return_arrow_whitespace
  - void_return
  - trailing_semicolon
  - switch_case_alignment
  - vertical_parameter_alignment
  - leading_whitespace
  - implicit_getter
  - unused_enumerated
  - legacy_constructor
  - mark
  - private_over_fileprivate
  - large_tuple
  - nesting
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - flatmap_over_map_reduce
  - last_where
  - sorted_first_last

empty_count:
  severity: warning

large_tuple:
  warning: 3
  error: 4

missing_docs:
  warning: [open, public]
  
closure_body_length:
  warning: 60
  error: 100

function_body_length:
  warning: 100
  error: 250

file_length:
  warning: 2100
  error: 6100

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 18
  error: 35
  
nesting:
  type_level: 2
  statement_level: 5

excluded:
  - Pods
  - build
  - Samples
  - ChartViewSample
  - SciChart
  - scripts
