name: iOS Lilly Device CI Lint, Unit Test and Summary

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
        targetName:
            type: string
        workspaceName:
            type: string
            
jobs:
  LINTING-AND-UNIT-TEST:
    uses: EliLillyCo/DIGH_SHARED_ACTIONS/.github/workflows/iOS_lint_unit-test.yml@main
    with:
      targetName: LillyDevice
      workspaceName: LillyDevice.xcworkspace
    secrets: inherit
    if: always()
  
  CI-SUMMARY:
    needs: LINTING-AND-UNIT-TEST
    uses: EliLillyCo/DIGH_SHARED_ACTIONS/.github/workflows/iOS_ci_summary.yml@main
    secrets: inherit
