name: CI/CD With generic reusable script with buils and test.

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        targetName:
            type: string
        workspaceName:
            type: string


jobs:
    pod_integrity:
        - name: Pod Integrity Stage
          run: git diff --name-only remotes/origin/main..artifact_test > git_diff.txt
    artifact:
        uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBuildSharedAction.yml@main
        with:
          targetName: POC_GithuAction
          workspaceName: POC_GithuAction.xcworkspace
    artifact_upload:
        needs: artifact
        uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOS_ci_summary.yml@main
        secrets: inherit
