name: CI/CD With generic reusable script with buils and test.

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
    targetName:
        type: string
    workspaceName:
        type: string


jobs:
    linting:
        uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBasicSharedActionLint.yml@main
        with:
          targetName: POC_GithuAction
          workspaceName: POC_GithuAction.xcworkspace
      
    build-app:
        uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBasicSharedActionCleanAndBuild.yml@main
        with:
          targetName: POC_GithuAction
          workspaceName: POC_GithuAction.xcworkspace

    test-app:
        uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBasicSharedActionTesting.yml@main
        with:
          targetName: POC_GithuAction
          workspaceName: POC_GithuAction.xcworkspace


