name: CI/CD With generic reusable script with buils and test.

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:
      inputs:
        targetName:
            type: string
        workspaceName:
            type: string

  

jobs:
  call-workflow:
    name: Instal dependecy and lint
    uses: mohanraajsk/POC_Shared_Actions/.github/workflows/LillyDevice_Linting.yml@main
    with:
      targetName: POC_GithuAction
      workspaceName: POC_GithuAction.xcworkspace
      
#    name: Build
#    uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBasicSharedActionCleanAndBuild.yml@main
#    with:
#      targetName: POC_GithuAction
#      workspaceName: POC_GithuAction.xcworkspace
#    
#    name: Test
#    uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBasicSharedActionTesting.yml@main
#    with:
#      targetName: POC_GithuAction
#      workspaceName: POC_GithuAction.xcworkspace
#    

