name: iOS Lilly Device CI Lint, Unit Test and Summary

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # inputs:
    #     targetName:
    #         type: string
    #     workspaceName:
    #         type: string
            
jobs:
  PR-CHECK:
    uses: mohanraajsk/POC_Shared_Actions/.github/workflows/prcheck.yml@main
    secrets: inherit
    if: always()
