name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode (Force open)
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
      
    - name: List of simulator
      run: xcrun simctl list
      
#    - name: Open simulator
#      run: open -a Simulator --args -CurrentDeviceUDID E7358E62-ECF9-436A-834F-CFB7C2801FD9

    - name: Build and test
      run: xcodebuild clean build test -workspace POC_GithuAction.xcworkspace -scheme "POC_GithuAction" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
