name: CI/CD With generic reusable script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-workflow:
    uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBasicSharedAction.yml@main
    with:
      targetName: POC_GithuAction
      workspaceName: POC_GithuAction.xcworkspace
