name: CI/CD With generic reusable script with pod cache and linting.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
      inputs:
        targetName:
        type: string
        required: true
      workspaceName:
        type: string
        required: true

jobs:
  call-workflow:
    name: Build and Test
    uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBasicSharedAction.yml@main
    with:
      targetName: POC_GithuAction
      workspaceName: POC_GithuAction.xcworkspace

