name: CI/CD With generic reusable script with buils and test.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        targetName:
            type: string
        workspaceName:
            type: string

jobs:
  call-workflow:
    name: Build
    uses: mohanraajsk/POC_Shared_Actions/.github/workflows/iOSBuildSeperatedSharedAction.yml@main
    with:
      targetName: POC_GithuAction
      workspaceName: POC_GithuAction.xcworkspace
    

